-- ============================================================
-- FieldTrack 2.0 — Production Schema Migration
-- Run once on a blank Supabase project.
-- No seed data. No test data.
-- After running: create your first org + admin via the app.
-- ============================================================

-- ══════════════════════════════════════════════════════════════
-- EXTENSIONS
-- ══════════════════════════════════════════════════════════════

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "pg_cron";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";

-- ══════════════════════════════════════════════════════════════
-- ENUMS
-- ══════════════════════════════════════════════════════════════

CREATE TYPE public.user_role AS ENUM ('ADMIN', 'EMPLOYEE');

CREATE TYPE public.expense_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

CREATE TYPE public.distance_job_status AS ENUM (
  'pending',
  'processing',
  'done',
  'failed'
);

-- ══════════════════════════════════════════════════════════════
-- SEQUENCES
-- ══════════════════════════════════════════════════════════════

-- Collision-safe employee code generator (EMP#### / ADM####)
-- Starts at 1. Shared across both prefixes — sequence value is the number,
-- prefix is determined at insert time by role.
CREATE SEQUENCE IF NOT EXISTS public.employee_code_seq
  START WITH 1
  INCREMENT BY 1
  NO CYCLE;

-- ══════════════════════════════════════════════════════════════
-- TABLES
-- ══════════════════════════════════════════════════════════════

-- ── organizations ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.organizations (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT        NOT NULL,
  slug       TEXT        UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.organizations IS
  'Top-level tenant. All other tables scope to organization_id.';

-- ── users ────────────────────────────────────────────────────
-- Mirrors auth.users but scoped to an organization with a role.
-- This is the application user table (not auth.users directly).
CREATE TABLE IF NOT EXISTS public.users (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  email           TEXT        NOT NULL UNIQUE,
  role            public.user_role NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.users IS
  'Application user profiles linked to auth.users via shared UUID and email.';

-- ── employees ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.employees (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id  UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id          UUID        UNIQUE REFERENCES public.users(id) ON DELETE SET NULL,
  name             TEXT        NOT NULL,
  phone            TEXT,
  is_active        BOOLEAN     NOT NULL DEFAULT true,
  employee_code    TEXT        NOT NULL UNIQUE,
  last_activity_at TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON COLUMN public.employees.employee_code IS
  'Human-readable identifier e.g. EMP0001 or ADM0001. Generated by sequence. UUID id is the PK.';
COMMENT ON COLUMN public.employees.last_activity_at IS
  'Updated on check-in / check-out. Used to compute ACTIVE / RECENT / INACTIVE status.';

-- ── attendance_sessions ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.attendance_sessions (
  id                             UUID                       PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id                UUID                       NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  employee_id                    UUID                       NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  checkin_at                     TIMESTAMPTZ                NOT NULL DEFAULT now(),
  checkout_at                    TIMESTAMPTZ,
  distance_recalculation_status  public.distance_job_status NOT NULL DEFAULT 'pending',
  total_distance_km              FLOAT8,
  total_duration_seconds         INT,
  created_at                     TIMESTAMPTZ                NOT NULL DEFAULT now(),
  updated_at                     TIMESTAMPTZ                NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.attendance_sessions IS
  'One row per field session (check-in to check-out). Source for GPS trails and distance jobs.';

-- ── gps_locations ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.gps_locations (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  session_id      UUID        NOT NULL REFERENCES public.attendance_sessions(id) ON DELETE CASCADE,
  employee_id     UUID        NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  latitude        FLOAT8      NOT NULL CHECK (latitude  >= -90  AND latitude  <= 90),
  longitude       FLOAT8      NOT NULL CHECK (longitude >= -180 AND longitude <= 180),
  accuracy        FLOAT8,
  recorded_at     TIMESTAMPTZ NOT NULL,
  sequence_number INT,
  is_duplicate    BOOLEAN     NOT NULL DEFAULT false,
  UNIQUE (session_id, recorded_at)
);

COMMENT ON TABLE public.gps_locations IS
  'Raw GPS breadcrumb trail per session. Duplicate flag set by distance calculation job.';

-- ── expenses ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.expenses (
  id              UUID                   PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID                   NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  employee_id     UUID                   NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  amount          NUMERIC                NOT NULL CHECK (amount > 0),
  description     TEXT                   NOT NULL,
  status          public.expense_status  NOT NULL DEFAULT 'PENDING',
  receipt_url     TEXT,
  submitted_at    TIMESTAMPTZ            NOT NULL DEFAULT now(),
  reviewed_at     TIMESTAMPTZ,
  reviewed_by     UUID                   REFERENCES public.users(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ            NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ            NOT NULL DEFAULT now()
);

-- ── session_summaries ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.session_summaries (
  id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id        UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  session_id             UUID        NOT NULL UNIQUE REFERENCES public.attendance_sessions(id) ON DELETE CASCADE,
  total_distance_km      FLOAT8      NOT NULL DEFAULT 0,
  total_duration_seconds INT         NOT NULL DEFAULT 0,
  avg_speed_kmh          FLOAT8      NOT NULL DEFAULT 0,
  computed_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.session_summaries IS
  'Computed distance/duration/speed per session. Written by BullMQ distance recalculation job.';

-- ── admin_sessions ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.admin_sessions (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id        UUID        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  organization_id UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  started_at      TIMESTAMPTZ NOT NULL,
  ended_at        TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.admin_sessions IS
  'Tracks when an admin started/stopped monitoring employees. Audit and compliance trail.';

-- ── employee_daily_metrics ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public.employee_daily_metrics (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  employee_id     UUID        NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  date            DATE        NOT NULL,
  sessions        INT         NOT NULL DEFAULT 0,
  distance_km     FLOAT8      NOT NULL DEFAULT 0,
  duration_seconds INT        NOT NULL DEFAULT 0,
  expenses_count  INT         NOT NULL DEFAULT 0,
  expenses_amount NUMERIC     NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_employee_daily_metrics UNIQUE (employee_id, date)
);

COMMENT ON TABLE public.employee_daily_metrics IS
  'Pre-aggregated daily metrics per employee. Powers leaderboards and analytics dashboards.
   Upserted by API on checkout and expense submission.';

-- ── org_daily_metrics ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.org_daily_metrics (
  id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id        UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  date                   DATE        NOT NULL,
  total_sessions         INT         NOT NULL DEFAULT 0,
  total_distance_km      FLOAT8      NOT NULL DEFAULT 0,
  total_duration_seconds INT         NOT NULL DEFAULT 0,
  active_employees       INT         NOT NULL DEFAULT 0,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_org_daily_metrics UNIQUE (organization_id, date)
);

COMMENT ON TABLE public.org_daily_metrics IS
  'Pre-aggregated daily metrics per organization. Powers org-level trend charts.
   Rolled up from employee_daily_metrics by API.';

-- ── employee_latest_sessions ─────────────────────────────────
CREATE TABLE IF NOT EXISTS public.employee_latest_sessions (
  employee_id            UUID        PRIMARY KEY REFERENCES public.employees(id) ON DELETE CASCADE,
  organization_id        UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  session_id             UUID        REFERENCES public.attendance_sessions(id) ON DELETE SET NULL,
  latest_checkin         TIMESTAMPTZ,
  latest_checkout        TIMESTAMPTZ,
  total_distance_km      FLOAT8,
  total_duration_seconds INT,
  status                 TEXT        CHECK (status IN ('ACTIVE', 'RECENT', 'INACTIVE')),
  updated_at             TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.employee_latest_sessions IS
  'Snapshot of each employee''s latest session state. Source of truth for dashboard reads.
   One row per employee, maintained automatically by triggers.
   NEVER scan attendance_sessions for dashboard queries — read from here instead.
   Status lifecycle: ACTIVE (trigger) → RECENT (trigger) → INACTIVE (pg_cron hourly).';

-- ══════════════════════════════════════════════════════════════
-- INDEXES
-- ══════════════════════════════════════════════════════════════

-- users
CREATE INDEX IF NOT EXISTS idx_users_org
  ON public.users (organization_id);

-- employees
CREATE INDEX IF NOT EXISTS idx_employees_org
  ON public.employees (organization_id);
CREATE INDEX IF NOT EXISTS idx_employees_user
  ON public.employees (user_id);
CREATE INDEX IF NOT EXISTS idx_employees_code
  ON public.employees (employee_code);

-- attendance_sessions
CREATE INDEX IF NOT EXISTS idx_sessions_employee
  ON public.attendance_sessions (employee_id);
CREATE INDEX IF NOT EXISTS idx_sessions_org_employee
  ON public.attendance_sessions (organization_id, employee_id);
CREATE INDEX IF NOT EXISTS idx_sessions_org_time
  ON public.attendance_sessions (organization_id, checkin_at);
CREATE INDEX IF NOT EXISTS idx_sessions_org_emp_checkin
  ON public.attendance_sessions (organization_id, employee_id, checkin_at DESC);

-- Partial index: one active session per employee (enforced + fast lookup)
CREATE UNIQUE INDEX IF NOT EXISTS uniq_active_session
  ON public.attendance_sessions (employee_id)
  WHERE checkout_at IS NULL;

-- Partial index: BullMQ distance recalculation job queue
CREATE INDEX IF NOT EXISTS idx_sessions_requeue
  ON public.attendance_sessions (checkout_at)
  WHERE checkout_at IS NOT NULL
    AND distance_recalculation_status IN ('pending', 'failed');

-- gps_locations
CREATE INDEX IF NOT EXISTS idx_locations_org
  ON public.gps_locations (organization_id);
CREATE INDEX IF NOT EXISTS idx_locations_session_time
  ON public.gps_locations (session_id, recorded_at);
CREATE INDEX IF NOT EXISTS idx_locations_session_sequence
  ON public.gps_locations (session_id, sequence_number);
CREATE INDEX IF NOT EXISTS idx_locations_employee_time
  ON public.gps_locations (employee_id, recorded_at);

-- expenses
CREATE INDEX IF NOT EXISTS idx_expenses_employee
  ON public.expenses (employee_id);
CREATE INDEX IF NOT EXISTS idx_expenses_status
  ON public.expenses (status);
CREATE INDEX IF NOT EXISTS idx_expenses_org_status
  ON public.expenses (organization_id, status);
CREATE INDEX IF NOT EXISTS idx_expenses_org_submitted
  ON public.expenses (organization_id, submitted_at);
CREATE INDEX IF NOT EXISTS idx_expenses_org_employee
  ON public.expenses (organization_id, employee_id);

-- session_summaries
CREATE INDEX IF NOT EXISTS idx_summaries_org
  ON public.session_summaries (organization_id);
CREATE INDEX IF NOT EXISTS idx_summaries_session
  ON public.session_summaries (session_id);
CREATE INDEX IF NOT EXISTS idx_summaries_org_computed
  ON public.session_summaries (organization_id, computed_at);
CREATE INDEX IF NOT EXISTS idx_summaries_employee_distance
  ON public.session_summaries (organization_id, session_id);

-- admin_sessions
CREATE INDEX IF NOT EXISTS idx_admin_sessions_admin
  ON public.admin_sessions (admin_id);
CREATE INDEX IF NOT EXISTS idx_admin_sessions_org_time
  ON public.admin_sessions (organization_id, started_at);

-- One active monitoring session per admin at a time
CREATE UNIQUE INDEX IF NOT EXISTS one_active_monitoring_session
  ON public.admin_sessions (admin_id)
  WHERE ended_at IS NULL;

-- employee_daily_metrics
CREATE INDEX IF NOT EXISTS idx_emp_daily_org_date
  ON public.employee_daily_metrics (organization_id, date);
CREATE INDEX IF NOT EXISTS idx_emp_daily_employee_date
  ON public.employee_daily_metrics (employee_id, date);
CREATE INDEX IF NOT EXISTS idx_emp_daily_org_distance
  ON public.employee_daily_metrics (organization_id, distance_km DESC);

-- org_daily_metrics
CREATE INDEX IF NOT EXISTS idx_org_daily_org_date
  ON public.org_daily_metrics (organization_id, date);

-- employee_latest_sessions
CREATE INDEX IF NOT EXISTS idx_latest_sessions_org
  ON public.employee_latest_sessions (organization_id);
CREATE INDEX IF NOT EXISTS idx_latest_sessions_status
  ON public.employee_latest_sessions (status);
CREATE INDEX IF NOT EXISTS idx_latest_sessions_updated
  ON public.employee_latest_sessions (updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_latest_sessions_org_status
  ON public.employee_latest_sessions (organization_id, status);
CREATE INDEX IF NOT EXISTS idx_latest_sessions_org_status_updated
  ON public.employee_latest_sessions (organization_id, status, updated_at DESC);

-- ══════════════════════════════════════════════════════════════
-- FUNCTIONS
-- ══════════════════════════════════════════════════════════════

-- ── set_updated_at ───────────────────────────────────────────
-- Generic BEFORE UPDATE trigger to stamp updated_at = now()
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.set_updated_at() IS
  'Generic updated_at stamper. Attach as BEFORE UPDATE trigger to any table with updated_at.';

-- ── fn_auto_create_employee ──────────────────────────────────
-- Fires AFTER INSERT on public.users.
-- Automatically creates a linked employees row so every user has an employee profile.
-- Admins get ADM#### codes, employees get EMP#### codes.
CREATE OR REPLACE FUNCTION public.fn_auto_create_employee()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_code    TEXT;
  v_prefix  TEXT;
  v_seq_num BIGINT;
BEGIN
  v_prefix  := CASE WHEN NEW.role = 'ADMIN' THEN 'ADM' ELSE 'EMP' END;
  v_seq_num := nextval('public.employee_code_seq');
  v_code    := v_prefix || LPAD(v_seq_num::text, 4, '0');

  INSERT INTO public.employees (
    id, organization_id, user_id, name, phone,
    employee_code, is_active, last_activity_at, created_at, updated_at
  ) VALUES (
    gen_random_uuid(),
    NEW.organization_id,
    NEW.id,
    initcap(replace(split_part(NEW.email, '@', 1), '.', ' ')),
    NULL,
    v_code,
    true,
    NULL,
    now(),
    now()
  );

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.fn_auto_create_employee() IS
  'Auto-creates employees row on users INSERT.
   Role-aware prefix: ADMIN → ADM####, EMPLOYEE → EMP####.
   Uses employee_code_seq to prevent race conditions on concurrent signups.';

-- ── fn_update_employee_latest_session ────────────────────────
-- Fires AFTER INSERT OR UPDATE on attendance_sessions.
-- Upserts the employee_latest_sessions snapshot row.
-- Includes staleness guard: will not overwrite a newer session.
-- This is critical — BullMQ distance jobs update old sessions;
-- without the guard those updates would corrupt the snapshot.
CREATE OR REPLACE FUNCTION public.fn_update_employee_latest_session()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Staleness guard: skip if a newer session is already in the snapshot
  IF EXISTS (
    SELECT 1 FROM public.employee_latest_sessions els
    WHERE els.employee_id   = NEW.employee_id
      AND els.latest_checkin > NEW.checkin_at
      AND els.session_id    <> NEW.id
  ) THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.employee_latest_sessions (
    employee_id, organization_id, session_id,
    latest_checkin, latest_checkout,
    total_distance_km, total_duration_seconds,
    status, updated_at
  )
  VALUES (
    NEW.employee_id,
    NEW.organization_id,
    NEW.id,
    NEW.checkin_at,
    NEW.checkout_at,
    NEW.total_distance_km,
    NEW.total_duration_seconds,
    CASE
      WHEN NEW.checkout_at IS NULL                        THEN 'ACTIVE'
      WHEN NEW.checkout_at > now() - interval '24 hours' THEN 'RECENT'
      ELSE                                                     'INACTIVE'
    END,
    now()
  )
  ON CONFLICT (employee_id) DO UPDATE SET
    session_id             = EXCLUDED.session_id,
    organization_id        = EXCLUDED.organization_id,
    latest_checkin         = EXCLUDED.latest_checkin,
    latest_checkout        = EXCLUDED.latest_checkout,
    total_distance_km      = EXCLUDED.total_distance_km,
    total_duration_seconds = EXCLUDED.total_duration_seconds,
    status                 = EXCLUDED.status,
    updated_at             = now();

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.fn_update_employee_latest_session() IS
  'Maintains employee_latest_sessions snapshot on every attendance_sessions change.
   Staleness guard prevents BullMQ distance recalculation jobs on old sessions
   from overwriting a more recent session in the snapshot.';

-- ── fn_sync_summary_to_latest_session ────────────────────────
-- Fires AFTER INSERT OR UPDATE on session_summaries.
-- Patches computed distance and duration into the snapshot row,
-- but only if the summary belongs to the employee''s current latest session.
CREATE OR REPLACE FUNCTION public.fn_sync_summary_to_latest_session()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.employee_latest_sessions els
  SET
    total_distance_km      = NEW.total_distance_km,
    total_duration_seconds = NEW.total_duration_seconds,
    updated_at             = now()
  FROM public.attendance_sessions s
  WHERE s.id            = NEW.session_id
    AND els.employee_id = s.employee_id
    AND els.session_id  = NEW.session_id;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.fn_sync_summary_to_latest_session() IS
  'Patches distance/duration into employee_latest_sessions when session_summaries changes.
   Only applies if the summary belongs to the employee''s current latest session.';

-- ── get_org_latest_sessions ──────────────────────────────────
-- Paginated, filterable sessions query for the admin dashboard.
-- NOTE: This queries attendance_sessions directly for historical accuracy.
-- For the live dashboard snapshot, read employee_latest_sessions directly.
CREATE OR REPLACE FUNCTION public.get_org_latest_sessions(
  p_org_id UUID,
  p_status TEXT    DEFAULT 'all',
  p_limit  INTEGER DEFAULT 20,
  p_offset INTEGER DEFAULT 0
)
RETURNS TABLE (
  id                           UUID,
  employee_id                  UUID,
  organization_id              UUID,
  checkin_at                   TIMESTAMPTZ,
  checkout_at                  TIMESTAMPTZ,
  total_distance_km            FLOAT8,
  total_duration_seconds       INT,
  distance_recalculation_status TEXT,
  created_at                   TIMESTAMPTZ,
  updated_at                   TIMESTAMPTZ,
  employee_code                TEXT,
  employee_name                TEXT,
  activity_status              TEXT,
  total_count                  BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  WITH latest AS (
    SELECT DISTINCT ON (s.employee_id)
      s.id, s.employee_id, s.organization_id,
      s.checkin_at, s.checkout_at,
      s.total_distance_km, s.total_duration_seconds,
      s.distance_recalculation_status::TEXT,
      s.created_at, s.updated_at,
      e.employee_code,
      e.name AS employee_name,
      CASE
        WHEN s.checkout_at IS NULL                        THEN 'ACTIVE'
        WHEN s.checkout_at > NOW() - INTERVAL '24 hours' THEN 'RECENT'
        ELSE                                                   'INACTIVE'
      END AS activity_status
    FROM attendance_sessions s
    JOIN employees e ON e.id = s.employee_id
    WHERE s.organization_id = p_org_id
    ORDER BY s.employee_id, s.checkin_at DESC
  ),
  filtered AS (
    SELECT * FROM latest
    WHERE
      p_status = 'all'
      OR (p_status = 'active'   AND activity_status = 'ACTIVE')
      OR (p_status = 'recent'   AND activity_status = 'RECENT')
      OR (p_status = 'inactive' AND activity_status = 'INACTIVE')
  ),
  counted AS (
    SELECT *, COUNT(*) OVER() AS total_count
    FROM filtered
    ORDER BY
      CASE activity_status
        WHEN 'ACTIVE'  THEN 1
        WHEN 'RECENT'  THEN 2
        ELSE                3
      END,
      checkin_at DESC
  )
  SELECT * FROM counted
  LIMIT p_limit OFFSET p_offset;
END;
$$;

COMMENT ON FUNCTION public.get_org_latest_sessions(UUID, TEXT, INTEGER, INTEGER) IS
  'Paginated admin sessions dashboard query. Returns latest session per employee
   with activity_status and total_count for pagination.
   p_status: ''all'' | ''active'' | ''recent'' | ''inactive''';

-- ══════════════════════════════════════════════════════════════
-- TRIGGERS
-- ══════════════════════════════════════════════════════════════

-- updated_at stamps
CREATE TRIGGER trg_updated_at_organizations
  BEFORE UPDATE ON public.organizations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_updated_at_users
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_updated_at_employees
  BEFORE UPDATE ON public.employees
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_updated_at_sessions
  BEFORE UPDATE ON public.attendance_sessions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_updated_at_expenses
  BEFORE UPDATE ON public.expenses
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_updated_at_summaries
  BEFORE UPDATE ON public.session_summaries
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Auto-create employee row on user signup
CREATE TRIGGER trg_auto_create_employee
  AFTER INSERT ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.fn_auto_create_employee();

-- Sync snapshot on session change
CREATE TRIGGER trg_update_employee_latest_session
  AFTER INSERT OR UPDATE OF checkin_at, checkout_at, total_distance_km, total_duration_seconds
  ON public.attendance_sessions
  FOR EACH ROW EXECUTE FUNCTION public.fn_update_employee_latest_session();

-- Sync distance/duration into snapshot when summary computed
CREATE TRIGGER trg_sync_summary_to_latest_session
  AFTER INSERT OR UPDATE OF total_distance_km, total_duration_seconds
  ON public.session_summaries
  FOR EACH ROW EXECUTE FUNCTION public.fn_sync_summary_to_latest_session();

-- ══════════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY
-- ══════════════════════════════════════════════════════════════

ALTER TABLE public.organizations          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_sessions    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gps_locations          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_summaries      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_sessions         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_daily_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.org_daily_metrics      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_latest_sessions ENABLE ROW LEVEL SECURITY;

-- ── Helper: org isolation ────────────────────────────────────
-- Reused pattern: user can only see rows in their own organization.
-- Resolves org via public.users where id = auth.uid().

CREATE POLICY "org_isolation_organizations"
  ON public.organizations FOR ALL
  USING (id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

CREATE POLICY "org_isolation_users"
  ON public.users FOR ALL
  USING (organization_id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

CREATE POLICY "org_isolation_employees"
  ON public.employees FOR ALL
  USING (organization_id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

CREATE POLICY "org_isolation_attendance_sessions"
  ON public.attendance_sessions FOR ALL
  USING (organization_id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

CREATE POLICY "org_isolation_gps_locations"
  ON public.gps_locations FOR ALL
  USING (organization_id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

CREATE POLICY "org_isolation_expenses"
  ON public.expenses FOR ALL
  USING (organization_id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

CREATE POLICY "org_isolation_session_summaries"
  ON public.session_summaries FOR ALL
  USING (organization_id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

CREATE POLICY "org_isolation_admin_sessions"
  ON public.admin_sessions FOR ALL
  USING (organization_id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

CREATE POLICY "org_isolation_employee_daily_metrics"
  ON public.employee_daily_metrics FOR ALL
  USING (organization_id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

CREATE POLICY "org_isolation_org_daily_metrics"
  ON public.org_daily_metrics FOR ALL
  USING (organization_id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

-- employee_latest_sessions: two policies
-- Admins: read/write all rows in their org
CREATE POLICY "els_admin_all"
  ON public.employee_latest_sessions FOR ALL
  USING (organization_id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

-- Employees: read only their own snapshot row
CREATE POLICY "els_employee_self"
  ON public.employee_latest_sessions FOR SELECT
  USING (employee_id = (SELECT id FROM public.employees WHERE user_id = auth.uid()));

-- ══════════════════════════════════════════════════════════════
-- PG_CRON — STATUS REFRESH JOB
-- ══════════════════════════════════════════════════════════════
-- Flips RECENT → INACTIVE after 24 hours of inactivity.
-- Runs every hour at :00.
-- ACTIVE → RECENT transition is handled instantly by the trigger.
-- RECENT → INACTIVE cannot be done by a trigger (time-based) so uses cron.

DO $outer$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM cron.job WHERE jobname = 'employee-status-refresh'
  ) THEN
    PERFORM cron.schedule(
      'employee-status-refresh',
      '0 * * * *',
      $cron$
        UPDATE public.employee_latest_sessions
        SET
          status     = 'INACTIVE',
          updated_at = now()
        WHERE status          = 'RECENT'
          AND latest_checkout < now() - interval '24 hours';
      $cron$
    );
  END IF;
END;
$outer$;

-- ══════════════════════════════════════════════════════════════
-- DONE
-- ══════════════════════════════════════════════════════════════
-- After running this migration on your new Supabase project:
--
-- 1. Create your first organization row:
--    INSERT INTO public.organizations (name, slug) VALUES ('Your Org', 'your-org');
--
-- 2. Register your first admin via Supabase Auth + your API.
--    The trigger will auto-create an employees row (ADM0001).
--
-- 3. All subsequent signups auto-create employee rows (EMP0001, EMP0002...).
--
-- 4. No seed data included — this is a clean production schema.
--
-- Tables:     11
-- Indexes:    54
-- Triggers:   9
-- Functions:  5
-- RLS:        12 policies across all 11 tables
-- Cron:       1 job (employee-status-refresh, hourly)
-- Extensions: uuid-ossp, pgcrypto, pg_cron, pg_stat_statements
-- ══════════════════════════════════════════════════════════════